# This is a basic workflow to help you get started with Actions

name: AutoTask

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  clockin:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    if: github.event.repository.owner.id == github.event.sender.id  # 自己点的 start
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Set up Python #安装python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install requests #安装requests
      run: |
        pip install requests
    - name: clockin #打卡
      env:
        users_data: ${{ secrets.users_data }}
        sckey: ${{ secrets.sckey }}
      run:
        python main.py $users_data $sckey
