# This is a basic workflow to help you get started with Actions

name: AutoTask

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '2 23 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  clockin:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    if: github.event.repository.owner.id == github.event.sender.id  # 自己点的 start
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Set up Python #安装python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install requests #安装requests
      run: |
        pip install requests
    - name: Install beautifulsoup4  #安装requests
      run: |
        pip install Beautifulsoup4==4.9.3
    - name: Install splinter #安装requests
      run: |
        pip install splinter==0.17.0
    - name: Install selenium #安装requests
      run: |
        pip install selenium==3.141.0
    - name: Install lxml #安装requests
      run: |
        pip install lxml
    - name: clockin #打卡
      env:
        users_data: ${{ secrets.users_data }}
        sckey: ${{ secrets.sckey }}
        usr_info: ${{ secrets.usr_info }}
      run:
#        python daily_check_upload.py $users_data $sckey $usr_info
        python daily_check_upload.py $usr_info
